deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: kirsing123/configserver
  tag: v3

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

appname_enabled: true
config_enabled: false
serviceregistry_enabled: false
otel_enabled: true
rabbitmq_enabled: false
orderdb_enabled: false
paymentdb_enabled: false
productdb_enabled: false