deploymentName: messageservice-deployment
serviceName: messageservice
appLabel: messageservice
appName: messageservice

replicaCount: 1

image:
  repository: kirsing123/messageservice
  tag: v3

containerPort: 9010

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

appname_enabled: true
config_enabled: false
serviceregistry_enabled: false
otel_enabled: false
rabbitmq_enabled: true
orderdb_enabled: false
paymentdb_enabled: false
productdb_enabled: false