server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3308/paymentdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENTSERVICE
  config:
    import: optional:configserver:http://localhost:8071/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-74127808.okta.com/oauth2/default
    audience: api://default
#okta:
#  oauth2:
#    issuer: https://dev-74127808.okta.com/oauth2/default
#    audience: api://default
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
