services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  orderdb:
    container_name: orderdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: orderdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  productdb:
    container_name: productdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: productdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  paymentdb:
    container_name: paymentdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: paymentdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "kirsing123/configserver:v1"
    container_name: configserver-microservice
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  serviceregistry:
    image: 'kirsing123/serviceregistry:v1'
    container_name: serviceregistry-microservice
    ports:
      - '8070:8070'
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "serviceregistry"

  cloudgateway:
    image: "kirsing123/cloudgateway:v1"
    container_name: cloudgateway-microservice
    ports:
      - "8072:8072"
    depends_on:
      serviceregistry:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cloudgateway"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  productservice:
    image: "kirsing123/productservice:v1"
    container_name: product-microservice
    ports:
      - "8080:8080"
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "productservice"
      SPRING_DATASOURCE_URL: "jdbc:mysql://productdb:3306/productdb"
    depends_on:
      productdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  paymentservice:
    image: "kirsing123/paymentservice:v1"
    container_name: payment-microservice
    ports:
      - "9000:9000"
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "paymentservice"
      SPRING_DATASOURCE_URL: "jdbc:mysql://paymentdb:3306/paymentdb"
    depends_on:
      paymentdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  orderservice:
    image: "kirsing123/orderservice:v1"
    container_name: order-microservice
    ports:
      - "8090:8090"
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "orderservice"
      SPRING_DATASOURCE_URL: "jdbc:mysql://orderdb:3306/orderdb"
    depends_on:
      orderdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  kirsing:
    driver: "bridge"