spring:
  application:
    name: cloudgateway
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      routes:
        - id : ORDERSERVICE
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/order/**
        - id: PAYMENTSERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: PRODUCTSERVICE
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/product/**
okta:
  oauth2:
    issuer: https://dev-74127808.okta.com/oauth2/default
    audience: api://default
    client-id: 0oagkty5nuUAPuvbZ5d7
    client-secret: YU4A_jaijcmtbrF0x4jxb22gphZi8W3Ldew1gcQsojt_2oIMoUNKK0EjNvHCAs3z
    scopes: openid, profile, email, offline_access
