apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceregistry-deployment
  labels:
    app: serviceregistry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceregistry
  template:
    metadata:
      labels:
        app: serviceregistry
    spec:
      containers:
        - name: serviceregistry
          image: kirsing123/serviceregistry:v3
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: storeapp-configmap
                  key: EUREKA_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: storeapp-configmap
                  key: SPRING_CONFIG_IMPORT
---
apiVersion: v1
kind: Service
metadata:
  name: serviceregistry
spec:
  selector:
    app: serviceregistry
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070