apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudgateway-deployment
  labels:
    app: cloudgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudgateway
  template:
    metadata:
      labels:
        app: cloudgateway
    spec:
      containers:
        - name: cloudgateway
          image: kirsing123/cloudgateway:v3
          ports:
            - containerPort: 8072
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: storeapp-configmap
                  key: CLOUDGATEWAY_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: storeapp-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: storeapp-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: cloudgateway
spec:
  selector:
    app: cloudgateway
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8072
      targetPort: 8072