server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3307/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDERSERVICE
  config:
    import: optional:configserver:http://localhost:8071/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-74127808.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oagkty5nuUAPuvbZ5d7
            client-secret: YU4A_jaijcmtbrF0x4jxb22gphZi8W3Ldew1gcQsojt_2oIMoUNKK0EjNvHCAs3z
        provider:
          okta:
            issuer-uri: https://dev-74127808.okta.com/oauth2/default
okta:
  oauth2:
    issuer: https://dev-74127808.okta.com/oauth2/default
    audience: api://default



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
